apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: flask-app-test
  labels:
    name: flask-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flask-app-test
  template:
    metadata:
      name: flask-app-test
      labels:
        name: flask-app-test
    spec:
      containers:
        - name: flask-app-test
          image: gcr.io/gcp-poc-bell-bi/flask-app:v1.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 512Mi
          env:
            - name: DEBUG_MODE
              value: "1"